---
title: "ADABoost"
output: html_document
---

```{r}
library(tidyverse)
library(tree)
library(gbm)
```


```{r}
df <- read.csv("../data/new_clean.csv")

df$n_row <- seq(1:nrow(df))

set.seed(4231)
train = sample_frac(df, 0.8)
test = (-c(sort(train$n_row)))
test = df[c(test),]
train = select(train,-c(n_row))
test = select(test,-c(n_row))

train_0_1 <- filter(train, class != 2) %>% filter(class != 3)
train_0_2 <- filter(train, class != 1) %>% filter(class != 3)
train_0_3 <- filter(train, class != 1) %>% filter(class != 2)
train_1_2 <- filter(train, class != 0) %>% filter(class != 3)
train_1_3 <- filter(train, class != 0) %>% filter(class != 2)
train_2_3 <- filter(train, class != 0) %>% filter(class != 1)


```


```{r}
train_0_1$pseudo_class <- ifelse(train_0_1$class == 0, 0 ,1)
train_0_2$pseudo_class <- ifelse(train_0_2$class == 0, 0 ,1)
train_0_3$pseudo_class <- ifelse(train_0_3$class == 0, 0 ,1)
train_1_2$pseudo_class <- ifelse(train_1_2$class == 1, 1 ,0)
train_1_3$pseudo_class <- ifelse(train_1_3$class == 1, 1 ,0)
train_2_3$pseudo_class <- ifelse(train_2_3$class == 2, 1 ,0)

```


```{r}

set.seed(4231)

boosted_0_1 <- gbm(pseudo_class ~. -class,data=train_0_1,distribution="adaboost",n.trees=30000,interaction.depth=1)

boosted_0_2 <- gbm(pseudo_class ~. -class,data=train_0_2,distribution="adaboost",n.trees=30000,interaction.depth=1)

boosted_0_3 <- gbm(pseudo_class ~. -class,data=train_0_3,distribution="adaboost",n.trees=30000,interaction.depth=1)

boosted_1_2 <- gbm(pseudo_class ~. -class,data=train_1_2,distribution="adaboost",n.trees=30000,interaction.depth=1)

boosted_1_3 <- gbm(pseudo_class ~. -class,data=train_1_3,distribution="adaboost",n.trees=30000,interaction.depth=1)

boosted_2_3 <- gbm(pseudo_class ~. -class,data=train_2_3,distribution="adaboost",n.trees=30000,interaction.depth=1)


```


```{r}
pred_01 <- predict(boosted_0_1,newdata=test, trees=30000, type = "response")
pred_01 <- ifelse(pred_01 >= 0.5, 1, 0)

pred_02 <- predict(boosted_0_2,newdata=test, trees=30000, type = "response")
pred_02 <- ifelse(pred_02 >= 0.5, 2, 0)

pred_03 <- predict(boosted_0_3,newdata=test, trees=30000, type = "response")
pred_03 <- ifelse(pred_03 >= 0.5, 3, 0)

pred_12 <- predict(boosted_1_2,newdata=test, trees=30000, type = "response")
pred_12 <- ifelse(pred_12 >= 0.5, 1, 2)

pred_13 <- predict(boosted_1_3,newdata=test, trees=30000, type = "response")
pred_13 <- ifelse(pred_13 >= 0.5, 1, 3)

pred_23 <- predict(boosted_2_3,newdata=test, trees=30000, type = "response")
pred_23 <- ifelse(pred_23 >= 0.5, 2, 3)

```


```{r}
pred_df <- as.data.frame(cbind(as.vector(pred_01),as.vector(pred_02),as.vector(pred_03), as.vector(pred_12), as.vector(pred_13), as.vector(pred_23)))

colnames(pred_df) <- c("pred_01", "pred_02", "pred_03", "pred_12", "pred_13", "pred_23")

pred_df$count_rock <- apply(pred_df, 1, function(x) length(which(x==0)))

pred_df$count_scissors <- apply(pred_df, 1, function(x) length(which(x==1)))

pred_df$count_paper <- apply(pred_df, 1, function(x) length(which(x==2)))

pred_df$count_ok <- apply(pred_df, 1, function(x) length(which(x==3)))

pred_df$max <- apply(pred_df[,7:10], 1, function(x) which.max(x))

View(pred_df)

pred_df$pseudo_class <- ifelse(pred_df$max == 1, "Rock", ifelse(pred_df$max == 2, "Scissors", ifelse(pred_df$max == 3, "Paper", "OK")))

test$class_original <- ifelse(test$class == 0, "Rock", ifelse(test$class == 1, "Scissors", ifelse(test$class == 2, "Paper", "OK")))

table(factor(test$class_original), factor(pred_df$pseudo_class))

(2810 + 2886 + 3692 + 3642)/nrow(test)
```

