---
title: "Hand_Gestures_0_1"
output: html_document
---

```{r load-libraries, warning=FALSE, echo=TRUE, message=FALSE}

library(tidyverse)
library(tree)
library(gbm)
library(e1071)

```


```{r data_preprocessing, warning=FALSE, echo=TRUE, message=FALSE}

## 0: Rock, 1: Scissors, 2: Paper, 3: OK

col_names <- c()
counter <- 0
for(i in 1:8){
  for(j in 1:8){
    counter = counter + 1
    coln <- paste("M", i, "S", j, sep = "")
    col_names[counter] <- coln
  }
}
col_names[counter + 1] <- "class" 

X0 <- read_csv("../data/0.csv", col_names = FALSE)
colnames(X0) <- col_names
X0$class <- "Rock"
X0$n_row <- seq(1:nrow(X0))

X1 <- read_csv("../data/1.csv", col_names = FALSE)
colnames(X1) <- col_names
X1$class <- "Scissors"
X1$n_row <- seq(1:nrow(X1))

set.seed(4231)
train_X0 = sample_frac(X0, 0.8)
test_X0 = (-c(sort(train_X0$n_row)))
test_X0 = X0[c(test_X0),]
train_X0 = select(train_X0,-c(n_row))
test_X0 = select(test_X0,-c(n_row))

nrow(test_X0)

set.seed(4231)
train_X1 = sample_frac(X1, 0.8)
test_X1 = (-c(sort(train_X1$n_row)))
test_X1 = X1[c(test_X1),]
train_X1 = select(train_X1,-c(n_row))
test_X1 = select(test_X1,-c(n_row))

train <- as.data.frame(rbind(train_X0, train_X1))
train$class <- as.factor(train$class)
test <- as.data.frame(rbind(test_X0, test_X1))
test$class <- as.factor(test$class)
```


```{r pca, warning=FALSE, echo=TRUE, message=FALSE}

classes_train <- factor(train$class)
trainPCA <- prcomp(train[,-ncol(train)])
#saveRDS(trainPCA, "./trainPCA01.rds")

train <- cbind(train, trainPCA$x[,1:17])
plot(trainPCA$x[,c(2,1)], col = classes_train)

test.data <- predict(trainPCA, newdata = test)
test <- cbind(test, test.data[,1:17])

trainPCA$rotation[1:5,1:4]
std_dev <- trainPCA$sdev
pr_var <- std_dev^2
prop_varex <- pr_var/sum(pr_var)

plot(cumsum(prop_varex), xlab = "Principal Component",
     ylab = "Cumulative Proportion of Variance Explained",
     type = "b")

sum(prop_varex[1:17])
```

```{r radial_kernel, warning=FALSE, echo=TRUE, message=FALSE}

set.seed(1)
svmfit=svm(class~., data=select(train, class:PC17), kernel="radial", gamma=0.1, cost=2.7)

#plot(svmfit, train[,c("PC1", "PC2", "class")])

#tune.out=tune(svm, class~., data=sample_frac(select(train, class:PC17), 1), kernel="radial", ranges=list(cost=c(2.6,2.7,2.8,2.9),gamma=c(0.08,0.09,0.10,0.11)))

#summary(tune.out)

table(true=test$class, pred=predict(svmfit,newdata=select(test, class:PC17)))

#table(true=test$class, pred=predict(tune.out$best.model,newdata=select(test, class:PC17)))

#library(caret)
#saveRDS(svmfit, "./svmfit01.rds")

#svmfit <- readRDS("./svmfit01.rds")


```

