---
title: "4 Type Classification"
output: html_document
---

```{r load-libraries, warning=FALSE, echo=TRUE, message=FALSE}

library(tidyverse)
library(tree)
library(gbm)
library(e1071)

```

```{r data_preprocessing, warning=FALSE, echo=TRUE, message=FALSE}

## 0: Rock, 1: Scissors, 2: Paper, 3: OK

col_names <- c()
counter <- 0
for(i in 1:8){
  for(j in 1:8){
    counter = counter + 1
    coln <- paste("M", i, "S", j, sep = "")
    col_names[counter] <- coln
  }
}
col_names[counter + 1] <- "class" 

X0 <- read_csv("../data/0.csv", col_names = FALSE)
colnames(X0) <- col_names
X0$class <- "Rock"
X0$n_row <- seq(1:nrow(X0))

X1 <- read_csv("../data/1.csv", col_names = FALSE)
colnames(X1) <- col_names
X1$class <- "Scissors"
X1$n_row <- seq(1:nrow(X1))

X2 <- read_csv("../data/2.csv", col_names = FALSE)
colnames(X2) <- col_names
X2$class <- "Paper"
X2$n_row <- seq(1:nrow(X2))

X3 <- read_csv("../data/3.csv", col_names = FALSE)
colnames(X3) <- col_names
X3$class <- "OK"
X3$n_row <- seq(1:nrow(X3))

set.seed(4231)
train_X0 = sample_frac(X0, 0.8)
test_X0 = (-c(sort(train_X0$n_row)))
test_X0 = X0[c(test_X0),]
train_X0 = select(train_X0,-c(n_row))
test_X0 = select(test_X0,-c(n_row))

set.seed(4231)
train_X1 = sample_frac(X1, 0.8)
test_X1 = (-c(sort(train_X1$n_row)))
test_X1 = X1[c(test_X1),]
train_X1 = select(train_X1,-c(n_row))
test_X1 = select(test_X1,-c(n_row))

set.seed(4231)
train_X2 = sample_frac(X2, 0.8)
test_X2 = (-c(sort(train_X2$n_row)))
test_X2 = X2[c(test_X2),]
train_X2 = select(train_X2,-c(n_row))
test_X2 = select(test_X2,-c(n_row))

set.seed(4231)
train_X3 = sample_frac(X3, 0.8)
test_X3 = (-c(sort(train_X3$n_row)))
test_X3 = X3[c(test_X3),]
train_X3 = select(train_X3,-c(n_row))
test_X3 = select(test_X3,-c(n_row))

test <- as.data.frame(rbind(test_X0, test_X1, test_X2, test_X3))
test$class <- as.factor(test$class)

```

```{r training_3_type_classifier, warning=FALSE, echo=TRUE,message=FALSE}

train <- as.data.frame(rbind(train_X1, train_X2, train_X3))
train$class <- as.factor(train$class)

classes_train <- factor(train$class)
trainPCA123 <- prcomp(train[,-ncol(train)])
train <- cbind(train, trainPCA123$x[,1:32])

svmfit123=svm(class~., data=select(train, class:PC32), kernel="radial", gamma=0.1, cost=2.7)

```


```{r classification, warning=FALSE, echo=TRUE, message=FALSE}

trainPCA01 <- readRDS("./trainPCA01.rds")
trainPCA02 <- readRDS("./trainPCA02.rds")
trainPCA03 <- readRDS("./trainPCA03.rds")
trainPCA12 <- readRDS("./trainPCA12.rds")
trainPCA13 <- readRDS("./trainPCA13.rds")
trainPCA23 <- readRDS("./trainPCA23.rds")

test_01 <- test
test.data_01 <- predict(trainPCA01, newdata = test_01)
test_01 <- cbind(test_01, test.data_01[,1:17])

test_02 <- test
test.data_02 <- predict(trainPCA02, newdata = test_02)
test_02 <- cbind(test_02, test.data_02[,1:22])

test_03 <- test
test.data_03 <- predict(trainPCA03, newdata = test_03)
test_03 <- cbind(test_03, test.data_03[,1:17])

test_12 <- test
test.data_12 <- predict(trainPCA12, newdata = test_12)
test_12 <- cbind(test_12, test.data_03[,1:18])

test_13 <- test
test.data_13 <- predict(trainPCA13, newdata = test_13)
test_13 <- cbind(test_13, test.data_13[,1:32])

test_23 <- test
test.data_23 <- predict(trainPCA23, newdata = test_23)
test_23 <- cbind(test_23, test.data_23[,1:32])

test_123 <- test
test.data_123 <- predict(trainPCA123, newdata = test_123)
test_123 <- cbind(test_123, test.data_123[,1:32]) 

svmfit01 <- readRDS("./svmfit01.rds")
svmfit02 <- readRDS("./svmfit02.rds")
svmfit03 <- readRDS("./svmfit03.rds")
svmfit12 <- readRDS("./svmfit12.rds")
svmfit13 <- readRDS("./svmfit13.rds")
svmfit23 <- readRDS("./svmfit23.rds")


pred_01 <- predict(svmfit01,newdata=select(test_01, class:PC17))
pred_02 <- predict(svmfit02,newdata=select(test_02, class:PC22))
pred_03 <- predict(svmfit03,newdata=select(test_03, class:PC17))
pred_12 <- predict(svmfit12,newdata=select(test_12, class:PC18))
pred_13 <- predict(svmfit13,newdata=select(test_13, class:PC32))
pred_23 <- predict(svmfit23,newdata=select(test_23, class:PC32))
pred_123 <- predict(svmfit123,newdata=select(test_123, class:PC32))

pred_df <- as.data.frame(cbind(as.vector(pred_01),as.vector(pred_02),as.vector(pred_03), as.vector(pred_12), as.vector(pred_13), as.vector(pred_23), as.vector(pred_123)))

colnames(pred_df) <- c("pred_01", "pred_02", "pred_03", "pred_12", "pred_13", "pred_23", "pred_123")

pred_df$count_rock <- apply(pred_df[,1:6], 1, function(x) length(which(x=="Rock")))

pred_df$count_scissors <- apply(pred_df[,1:6], 1, function(x) length(which(x=="Scissors")))

pred_df$count_paper <- apply(pred_df[,1:6], 1, function(x) length(which(x=="Paper")))

pred_df$count_ok <- apply(pred_df[,1:6], 1, function(x) length(which(x=="OK")))

pred_df$max <- apply(pred_df, 1, function(x) which.max(x))

pred_df$pseudo_class <- ifelse(pred_df$max == 8, "Rock", ifelse((pred_df$count_scissors == 2 & pred_df$count_paper == 2 & pred_df$count_ok == 2), pred_123, ifelse(pred_df$max == 9, "Scissors", ifelse(pred_df$max == 10, "Paper", "OK"))))

pred_df$pseudo_class <- replace(pred_df$pseudo_class, which(pred_df$pseudo_class == 1), "OK")

pred_df$pseudo_class <- replace(pred_df$pseudo_class, which(pred_df$pseudo_class == 2), "Paper")

pred_df$pseudo_class <- replace(pred_df$pseudo_class, which(pred_df$pseudo_class == 3), "Scissors")

## With secondary classification for tie breaking of types 1, 2 and 3

table(factor(test$class), factor(pred_df$pseudo_class))

(508 + 476 + 570 + 450)/nrow(test)

## No Tie Breaking and assigning all ties to type 1

pred_df$pseudo_class <- ifelse(pred_df$max == 8, "Rock", ifelse(pred_df$max == 9, "Scissors", ifelse(pred_df$max == 10, "Paper", "OK")))

table(factor(test$class), factor(pred_df$pseudo_class))

(506 + 385 + 570 + 468)/nrow(test)

```